### ISSUE TITLE
Panel tile management problems

### ISSUE THREAD

**Issue by acauan** [Allsteel/awesome#230]
Now we can deal with our tiles like Generic Office and Fika does. But there are some problems since Generic Office and Fika are much simpler than Allsteel products.

- Glass tiles depend on the other side matching tile, how can we handle this?
- Tiles heights (sum of it all) does not match the panel height always because we have Stacking Frames.
- We have several tile types, which one with different height options. It could cause many invalid scenarios when splitting, merging or dragging tiles. If you change a type, it could affect the sum of all tiles heights.

**Comment by tucaz** [comment]
- [ ] Remove height property from tile selection
  - Tiles height can only be managed through merge/split connectors
- Tile types will be changed the way they are now. No need to do anything. The user will click on the desired tile and change the type.
  - [ ] There is a restriction, however, tile types have to be filtered according to the height of the selected tile. For example: glass tiles types should not be available on tiles taller than 30".
- [ ] When stretching a tile the height should be restricted to the available domain of the current tile type (I believe its what it does now - So no changes here too)
- [ ] When splitting or merging a tile if the resulting change is an invalid size/type it should be changed to the default which is tackable acoustic

**Comment by tucaz** [comment]
@jghines we have a few more questions given the scenario below:

- You have a 35"H panel with two 15"H stacker panel frames on top of it just like the image below

![image](https://user-images.githubusercontent.com/111954/31292651-e3a2edc2-aa99-11e7-92bd-15723fd00508.png)

- Once you place the stacker panel frames we will automatically add the tiles segmented (just like the image below so the user never sees the tiles like the image above)

![image](https://user-images.githubusercontent.com/111954/31292715-1948ae08-aa9a-11e7-859e-fc99a0bbd7ed.png)

- Our questions now are:

1. What is the expected behavior for the tiles if the user changes the height of one of the stacker panel frames? What if the frame that is changed is the one in the middle?
2. What happens if instead of having the standard segmentation (one tile per frame) the user changed it to a monolithic of 60" H and decides to adjust the height of the one of the stackers? What if it is the middle?
3. What if the user has a "crazy" segmentation that doesn't match the height of the stacking frames and the height of the stacking frame is changed?

**Comment by jghines** [comment]
@tucaz 
1. What is the expected behavior for the tiles if the user changes the height of one of the stacker panel frames? **_The tile size should change with the stacking frame size_** 
What if the frame that is changed is the one in the middle? **_The middle tile size should change to match the stacking frame that changed and the top stacking frame should adjust accordingly._**
![before](https://user-images.githubusercontent.com/31668449/31294625-3bee0e6a-aaa1-11e7-982e-a31d2901094e.PNG)
![after](https://user-images.githubusercontent.com/31668449/31294628-45edd620-aaa1-11e7-9cce-eb487e373b11.PNG)

2. What happens if instead of having the standard segmentation (one tile per frame) the user changed it to a monolithic of 60" H and decides to adjust the height of the one of the stackers? What if it is the middle? **_Keep the monolithic in the base position and add a tile above to fill the remaining space created from changing the size of the stacking frame._**

![before mono](https://user-images.githubusercontent.com/31668449/31294639-55091502-aaa1-11e7-9832-09e7980def01.PNG)
![after mono](https://user-images.githubusercontent.com/31668449/31294645-58ba0ce2-aaa1-11e7-942c-e101e237c9cf.PNG)

3. What if the user has a "crazy" segmentation that doesn't match the height of the stacking frames and the height of the stacking frame is changed? **_Can you give an example. I am not sure I understand what you are referring to here._**

**Comment by tucaz** [comment]
@jghines I'm sorry for the delay. We were trying to find a way to simplify the reasoning behind the process, but it is proven to be hard. We came up with 14 scenarios that we need to validate and see if we can think of a few rules to cover all of them.

Beware, the scenes you are about to see are going to confuse you for the rest of your life.

![image](https://user-images.githubusercontent.com/111954/31299612-e7a00048-aab4-11e7-9320-d8aa90fe9a5c.png)

The rules we came up so far are:

**Resizing**

1. For cases such as 1, 2 and 7 where the tile segmentation match exactly with the panel frames as the user drags each of the panel frames up or down (to increase or decrease the height) the tiles would follow
2. For cases such as the one on the rule above plus 3, 4, 5, 6, 8, 9, 10, 11, 12, 13 and 14 where at least one tile match the exactly the height of one panel frame we would resize the matching part of the tile as the user drags. For example: in case 8 if the user drags the base panel frame up (where a tile matches the height) we would make the first tile go up and follow the increase in size

**Removing Frames**

3. For cases such as 1 and 7 where the tiles are perfectly aligned if the user removes one of the stackers we will remove the matching tile because it would be a "clean cut"
4. For cases such as 2, 4, 5, 6, 9, 10, 12, 13 and 14 if the user removes the top most stacking frame the top most tile would absorb the difference in height and match the panel height. If the resulting tile is a invalid size (because of the type) we would change it to a default tackable acoustic

**Questions**

I think we covered most cases except in the rules except for the ones below.

5. For cases such as 3, if the user drags the top panel frame up what should happen? Increase the height of the top tile as much as allowed for the existing tile type?
6. For cases such as 5, if the middle stacker frame gets removed, should the tile spanning up be resized to just live inside the top stacker frame?
7. For 12, if the middle stacker is removed. Should we make the bottom-most tile resize to match the base panel frame? What do we do with the second tile, from the top, that will leave the top stacker frame uncovered?

I guess you got the idea. Please take a look at this and see what you think. We need to adopt a few rules as possible so we won't go crazy :P

**Comment by jghines** [comment]
@tucaz  Please see answers to your questions below. Let me know if any of this does not make sense. 

5.	For cases such as 3, if the user drags the top panel frame up what should happen? Increase the height of the top tile as much as allowed for the existing tile type? **_Yes, increase the top tile height. If the tile type becomes invalid due to size change to tackable acoustical._** 
6.	For cases such as 5, if the middle stacker frame gets removed, should the tile spanning up be resized to just live inside the top stacker frame? **_We would like to eliminate the ability for a user to remove a stacker from the middle. We want to force them to remove stackers from the top down. If they deleted the top stacker, then the middle stacker could be pulled up or down to change the size, or removed  if needed. The base tile should stay as-is, and top tile should adjust to match the overall height with stacker. If tile types become invalid due to size they would default back to tackable acoustical. In this example, base frame & tile are 35H, stacker & tile are 30”H._**
7.	For 12, if the middle stacker is removed. Should we make the bottom-most tile resize to match the base panel frame? What do we do with the second tile, from the top, that will leave the top stacker frame uncovered? ? **_Same logic as above. The user would have to remove the top stacker first and then adjust the middle stacker to whatever size they wanted, etc. The base tile should stay as-is, and top tile should adjust to match the overall height with stacker. If tile types become invalid due to size they would default back to tackable acoustical. In this example, base frame is 35H + base tile 50H, stacker is 30H + stacking tile is 15H._**
