### ISSUE TITLE
Elevations won't work

### ISSUE THREAD

**Issue by tucaz** [Allsteel/awesome#276]
## Steps

1. Place a panel
2. Place a seating product
3. Drop an elevation snapper from the symbols list

No elevation will be drawn

**Comment by acauan** [comment]
After some research, I think the problem is related to this error:

`@ cm.core3D.Instance3D.buildInstance: invalid primitive , Instance3D(0x00007FF6D96F01E8, prim=null, n=1, r=0)`

I believe this `prim=null` is preventing elevations to be rendered.

c:\CetDev\version8.0\home\cm\core3D\instance3D.cm, line 390

`if (primitive and primitive !in InvisiblePrimitive3D and !primitive.prim) {`

**Comment by tucaz** [comment]
Closed by #283
