### ISSUE TITLE
Autosize of worksurfaces will only work for rectangular shaped?

### ISSUE THREAD

**Issue by tucaz** [Allsteel/awesome#300]
When placing a 120 deg worksurface it won't automatically resize to the width of the panel like rectangular worksurfaces do.

## Steps

1. Place two 42" W panels at 120deg
2. Drag a Corner 120 deg to the corner

It won't resize automatically. 

![image](https://user-images.githubusercontent.com/111954/32307246-7f367c50-bf4d-11e7-8c8b-27a79026f828.png)

(Is there a generic way to make it "chupar" the width of the panel?)

**Comment by mbr4nt** [comment]
@tucaz the programmer has to tell the connectLine which prop it manipulates. In the case of the 120, what we have won't work because the connectLine size does not match the width. I'll need to make something different. same with any weird shape. Do you want me to go one by one in the worksurface tab and make them work?

**Comment by tucaz** [comment]
Seems to be fixed
